import type {Metadata} from "next";
import "./globals.scss";
import {Inter} from 'next/font/google';
import Header from "@/components/header";

const inter = Inter({subsets: ['latin'], display: 'swap'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className='header-wrapper'>
                <Header></Header>
            </div>
            <html lang="en" className={inter.className}>
            <body>{children}</body>
            </html>
        </>
    );
}
